### ISSUE TITLE
feat/singup,login,logout,delete 코드 리뷰

### ISSUE THREAD

**Issue by every-heyday** [chaewonni/FreshmanCommunity#3]
### 회원가입
Member.createMember
- 회원가입 request body에서 id를 포함시키지 않고 보내면(signupDto) 굳이 id가 null인지 여부를 확인하지 않아도 될 것 같습니다. 
- studentId에서 앞 2자리만 사용하는 이유가 따로 있을까요?

MemberService.signup
- 존재하지 않은 major을 넣는 경우 에러를 반환해주면 어떨까요?

### 로그인
MemberService.login
- 지금 로직은 return member가 if로 먼저 처리되는데, member == null 또는 비밀번호가 맞지 않는 경우 return null을 먼저 해야 합니다. 현재 코드로는 이메일은 틀린데 비밀번호가 맞은 경우 현재 성공으로 처리되기 때문입니다.
- 세션은 로그인이 성공하면 브라우저를 끄지 않는 이상 계속 세션 정보가 유지되기 때문에 만약 로그인을 실패하는 경우 session을 제거해주는 로직이 추가되면 안전할 것 같습니다.

### 회원탈퇴
MemberService.delete
- 멤버레포지토리에서 삭제 후, createMemberDto를 반환해주는 이유가 있을까요? 어차피 member는 null이 되서 return만 써도 되지 않을까요? 그 경우 void를 넣어주셔야 하고요.

### 전체
- (권장) uri와 클래스명을 일치시키는 게 코드의 가독성을 높일 수 있는 방법입니다. user/로 시작되는 컨트롤러에 member 객체에 대해 작성하는데 이왕이면 user/로 들어오는 요청은 user로 member 엔티티를 쓸 거라면 member/ 이런 식으로 URI를 통일해주는 것이 좋습니다.
- 전체적으로 입력값에 대해 유효성 검사를 추가해보면 프론트에서 한번, 백엔드 에서 한 번더 검증할 수 있으니 참고해주시면 좋겠습니다.
- 각각의 세부적인 에러 시 status 코드를 구분하고 메시지를 나눠서 반환해주셔야 합니다. 현재는 일부 에러가 500으로 뜨는 데 이 경우엔 프론트엔드에서 구체적으로 어떤 에러인지 확인하기 쉽지 않습니다. message도 trace로 리턴되는데 자세히 써주면 좋겠죠?

`전반적으로 로직 자체는 잘 구현하셔서, 세세한 유효성 검사나 에러 처리로 보완을 해주시는 걸 추천드립니다!`

**Comment by chaewonni** [comment]
헉 꼼꼼하게 리뷰해주셔서 정말 감사합니다! 리뷰해주신 것들 바탕으로 코드 수정하겠습니다!!
studentId에서 앞 2자리만 저장하는 이유는 댓글을 달면 ex) 컴퓨터공학과 21학번 이렇게 뜨게 되는데 유저의 학번 정보를 불러올 때 21만 불러오기 위해서 애초에 저장을 할 때부터 2자리만 저장하기 위함이었습니다..!

**Comment by chaewonni** [comment]
멘토님 혹시 머지를 먼저 한 후에 리뷰해주신 것들을 바탕으로 코드를 다시 고치고 다시 브랜치에 push하는 식으로 코드를 업로드해나가면 될까요,,?!

**Comment by every-heyday** [comment]
> 헉 꼼꼼하게 리뷰해주셔서 정말 감사합니다! 리뷰해주신 것들 바탕으로 코드 수정하겠습니다!! studentId에서 앞 2자리만 저장하는 이유는 댓글을 달면 ex) 컴퓨터공학과 21학번 이렇게 뜨게 되는데 유저의 학번 정보를 불러올 때 21만 불러오기 위해서 애초에 저장을 할 때부터 2자리만 저장하기 위함이었습니다..!

이 경우에는 처음부터 2자리 숫자만 프론트엔드에서 받도록 하고, 백엔드에선 substring 대신 string 길이로 2자리수 판단 후 저장하는 형태가 더 좋을 것 같습니다.

**Comment by every-heyday** [comment]
> 멘토님 혹시 머지를 먼저 한 후에 리뷰해주신 것들을 바탕으로 코드를 다시 고치고 다시 브랜치에 push하는 식으로 코드를 업로드해나가면 될까요,,?!

머지하지 않고 그냥 바로 해당 브랜치에서 코드 고친 다음 commit -> push 하는 형태로 업로드하면 됩니다

**Comment by chaewonni** [comment]
넵 알겠습니다 감사합니다!!

**Comment by chaewonni** [comment]
안녕하세요 멘토님! 각각의 세부적인 에러 시 status 코드를 구분하고 메시지를 나눠서 반환해야 한다고 해주셨는데 그럼 각각의 에러마다 예외 처리 클래스를 만들어 구현해야 하는 것인가요?? 그리고 trace로 return된다는 게 
![스크린샷 2024-02-07 오후 3 38 11](https://github.com/chaewonni/FreshmanCommunity/assets/113420297/061db403-b40b-4c11-8e01-143f0779c07d)
이런식으로 길게 출력되게 하지 말고 프론트에서 보기 간편하게 바꿔야 하는 것인가요??

**Comment by every-heyday** [comment]
> 안녕하세요 멘토님! 각각의 세부적인 에러 시 status 코드를 구분하고 메시지를 나눠서 반환해야 한다고 해주셨는데 그럼 각각의 에러마다 예외 처리 클래스를 만들어 구현해야 하는 것인가요?? 그리고 trace로 return된다는 게 ![스크린샷 2024-02-07 오후 3 38 11](https://private-user-images.githubusercontent.com/113420297/302883385-061db403-b40b-4c11-8e01-143f0779c07d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNTEwNzIsIm5iZiI6MTcwNzM1MDc3MiwicGF0aCI6Ii8xMTM0MjAyOTcvMzAyODgzMzg1LTA2MWRiNDAzLWI0MGItNGMxMS04ZTAxLTE0M2YwNzc5YzA3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQwMDA2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2JhZDQyYTAyZDgwZTlmNGQyMTgwNGU0ZTY3YjUwOWQwYWQwMTg1MjU3ZjBiYTE2OGRkNjFlNTQwNzUyNjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VYfA1ZKoK37_P00i8BLs6wX5de-roaALvIexR639Z2s) 이런식으로 길게 출력되게 하지 말고 프론트에서 보기 간편하게 바꿔야 하는 것인가요??

네, 말씀하신 방법으로 에외 처리를 할 수 있습니다.
그리고 trace 로만 리턴해도 큰 문제는 아니지만 프론트엔드 단에서 trace 의 string 메시지 (예. `이미 존재하는 회원입니다` 라는 데이터)를 확인하기 쉽지 않으니 이왕이면 custome으로 Exception 을 핸들링해주는 방향으로 의견을 드렸습니다.

**Comment by chaewonni** [comment]
![스크린샷 2024-02-08 오후 12 20 44](https://github.com/chaewonni/FreshmanCommunity/assets/113420297/c3ee5a5a-a28a-44fb-9dfb-985e7d2a76ab)
예외 클래스를 만들어 구현해보았는데요..! 굳이 statusCode가 body에 나타나지 않더라도 저 상단에 409conflict로 나타나게 해도 괜찮은건가요?

**Comment by chaewonni** [comment]
앗 그리고 모든 예외를 다 예외클래스를 만들어서 처리해주는 게 좋은가요 아니면 특정한 유형의 오류를 더 명확하게 표현하면 좋은 (중요하게 다뤄야 하는 비즈니스 로직 오류 위주) 오류들만 예외클래스를 만들어서 처리해주는 게 좋은가요??
